#!/usr/bin/env bash
# @Appname: olinst Offline install of homebrew and homebrew-cask install
# @version: 0.0.2
# @Description: this script will install homebrew and homebrew-cask files
# from a list stored in a hblist.csv and hbclist.csv
# @Usage:

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

brew_install_or_upgrade() {
  if brew_is_installed "$1"; then
    if brew_is_upgradable "$1"; then
      fancy_echo "Upgrading %s ..." "$1"
      brew upgrade "$@"
    else
      fancy_echo "Already using the latest version of %s. Skipping ..." "$1"
    fi
  else
    fancy_echo "Installing %s ..." "$1"
    brew install "$@"
    # todo: add in if failure to get file then try proxy
    # http_proxy=http://<proxyhost>:<proxyport> brew install $FORMULA
  fi
}

brew_is_installed() {
  brew list -1 | grep -Fqx "$1"
}

brew_is_upgradable() {
  ! brew outdated --quiet "$1" >/dev/null
}

# check if hblist.csv and hbclist.csv exist
# if files not found inform the user


# load the file

# check if install file exists
# create file list of install files not found for later download

function install_cask_file(){
    SaveIFS=$IFS
    IFS=","
    while read appName; do
    # echo "the first value is", ${appName}
    # fancy_echo "Checking if Application  \"${appName}\" is installed..."
    if brew cask list -1 | grep -Fqx ${appName}; then
        fancy_echo "${appName} is installed, skipping..."
    else
    # todo: if file does not exist then add to wishlist.txt for later download
    # when connected to internet
    #
        fancy_echo "Installing ${appName} ..."
        brew cask install ${appName}
    fi

    done < "$inputfile"
    IFS=$SaveIFS

}
function install_brew_file(){
    SaveIFS=$IFS
    IFS=","
    while read appName; do
    # echo "the first value is", ${appName}
    # fancy_echo "Checking if Application  \"${appName}\" is installed..."
    if brew list -1 | grep -Fqx ${appName}; then
        fancy_echo "${appName} is installed, skipping..."
    else
    # todo: if file does not exist then add to wishlist.txt for later download
    # when connected to internet
        fancy_echo "Installing ${appName} ..."
        brew install ${appName}
    fi

    done < "$inputfile"
    IFS=$SaveIFS

}
# check if appname is installed and skip if already installed
# log that the files are already installed.

# install the file

# log files that are installed on the computer

fancy_echo 'Checking for Homebrew Apps fileslist'
if [ -f "hblist.csv" ]; then
    fancy_echo "hblist.csv file found"
    inputfile="hblist.csv"
    install_brew_file
  else
    fancy_echo "hblist.csv file not found"
fi
fancy_echo 'Checking for Homebrew Cask Apps fileslist'
if [ -f "hbclist.csv" ]; then
    fancy_echo "hbclist.csv file found"
    inputfile="hbclist.csv"
    install_cask_file
  else
    fancy_echo "hbclist.csv file not found"
fi
